name: Clovemix
url: https://github.com/ashpatil07/clovemix-jekyll-theme
description: Jekyll version of Dopetrope html5 template.

permalink: /themes/:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
